### ISSUE TITLE
Sacrificing on Max buy will cause the buy options to mess up

### ISSUE THREAD

**Issue by luciferakathedevil** [wol-soft/beerplop#120]
When i sacrificed on max buy it caused my buy options to say what the max buy amount says but also if clicked max buy it would say what the previous buy cost was like example if i have 100x buy on then switch to max it would cause the max buy to show the price of buy 100 then not show the amount you can buy of that object(and if useful I'm on chrome OS

**Comment by wol-soft** [comment]
Fixed in version 1.69.0
