### ISSUE TITLE
Autobuy on Upgrades

### ISSUE THREAD

**Issue by Marcnesium87** [wol-soft/beerplop#39]
What about an Holy Upgrade or Unique Building (e.g Gize) that gives us an late Game option to automate Upgrades. Something intelligent, Maybe upgradeable to more inteligent. Something like first it is, "buy when affordable" and later with upgrades to buy only when Upgrade cost are 50%,40%,30%,20%10% of all Plops.

**Comment by wol-soft** [comment]
This relates to the upgrades of the main game?

**Comment by Marcnesium87** [comment]
Yes it does

**Comment by wol-soft** [comment]
Implemented auto upgrade control unlockable via beer factory academy exploration
