### ISSUE TITLE
Bekomme andauernd NaN bei den Magiern, wenn ich Auto-Trainings anschmeiße

### ISSUE THREAD

**Issue by papulla** [wol-soft/beerplop#54]
Seit dem ich im e+100 Mana per second Bereich bin, passiert es immer öfter, dass die Magier auf NaN stehen, bei der Ausbildungszeit.

Bin Aktuell in folgenden Leveln bei den:
Spells: LXXXIV
Equipment: XLVIII
Darkness: XLIV

Habe jetzt 572 Magier, davon trainieren so die Hälfte,

**Comment by 2ndK16** [comment]
Sei dankbar, warte 30 Sekunden, lade die Seite neu und das Training ist abgeschlossen.

**Comment by wol-soft** [comment]
Trotzdem immer noch ein Bug 😃

**Comment by wol-soft** [comment]
Die Trainings sind jetzt auf Max. 1000 Tage begrenzt. Zusätzlich wurde der Preis erhöht, um ein Beenden des Spiels mit Magiern, sobald ein bestimmter Schwellwert überschritten ist, zu unterbinden.
