### ISSUE TITLE
Eierbier!

### ISSUE THREAD

**Issue by 2ndK16** [wol-soft/beerplop#67]
Nicht vergessen: Ei als Zutat für die Beer Blender Bar! Kann vielleicht die Beer Factories boosten oder den Verkauf in der Automated Bar. Und dazu einen lecker Pillkaller!

**Comment by wol-soft** [comment]
'Kleiner' Step-By-Step Guide für die Implementierung. Da hängen doch schon einige Sachen mit dran. Mal schauen, was ich nun so alles vergessen hab 😄
Relativ wichtig für die Implementierung ist ein mögliches Refactoring in Schritt **5**

### 1

`src/client/js/Game/Minigames/BeerBlender.js`

Neuen Eintrag für neue Zutat anlegen. Hierbei wird definiert, welche Auswirkungen die Zutat auf das Spiel hat. Translation nicht vergessen `beerBlender.{$ingrediet}`

Wenn ein neuer Effekt definiert wird (zB. beerFactory), sicherstellen, dass Translations für die Effekte hinterlegt sind `beerBlender.{$effect}Up`, `beerBlender.{$effect}Down`

### 2

`src/View/Img/BeerBlender`

Neue Grafik für Zutat anlegen

### 3

`src/client/js/Game/Model/HolyUpgradeStorage.js`

Neuen Eintrag für Holy Upgrade mit Kosten, Koordinaten und Abhängigkeiten (aus den Daten wird der Graph gezeichnet).
upgrade Callback neue Zutat freischalten.

Die callbacks werden ausgeführt
- sobald man das Holy Upgrade erwirbt
- Das Holy Upgrade erworben ist und
  - Nach einem Sacrifice
  - Ein Spielstand geladen wird (oder Page-refresh). Hierbei wird den Funktionen als erster Parameter true übergeben um zwischen neu laden und Neuerwerb/Sacrifice unterscheiden zu können

Die Beer Blender Bar sorgt dafür, dass Zutaten nicht mehrfach freigeschaltet werden. Vgl. andere Zutaten

### 4

`src/View/Img/HolyUpgrades`

Grafik für das Holy Upgrade anlegen (am besten eine andere kopieren und bearbeiten, damit der Rahmen gleich bleibt)
Wichtig hierbei: ID (der key aus dem HolyUpgradeStorage) und die class `holy-upgrade-item` im SVG (vgl. andere)

### 5

`src/client/js/Game/Minigames/BeerBlender.js`

Effekt der Zutat implementieren:

Aktueller Effekt-Wert kann mit `getEffect` geholt werden.

Was soll das Holy Upgrade ändern? zB. Beer Factory Boost:
- Infrastruktur zum Boosten besteht bereits durch die Buff Bottle.
  Mechanik: src/client/js/Game/Controller/BuffController.js:511

Wert muss beim Neuladen und beim Verändern der Zutaten an Komponente übergeben werden (oder die Komponente, wie beispielsweise Beer Factories holt sich aktiv den aktuellsten Wert). Vgl. hierzu  `_rebuildModificationCache` und Constructor-Methode vom BeerBlender. Sorgt beides für Kopplung zwischen den Komponenten. Daher:
Wenn Beer Factory Boost implementiert werden soll, macht es vermutlich Sinn, den `multiplier` der Beer Factory auf einen ComposedValue umzubauen. Macht das Aktualisieren des Wertes beim Verändern der aktuellen Beer Blender Zutaten deutlich einfacher und entkoppelt die Komponenten.
Könnte auch als unabhängige Änderung vorher durchgeführt werden.

Vgl. hierzu: https://wol-soft.de/apps/beerplop/wiki/index.php/Composed_Value_Registry

**Comment by 2ndK16** [comment]
confeci
