### ISSUE TITLE
wol-soft.de down

### ISSUE THREAD

**Issue by MRVDH** [wol-soft/beerplop#72]
Website is down.

**Comment by wol-soft** [comment]
Hi @MRVDH thanks for the report. I can't find anything in the logs. For me everything seems fine. Can you access the page again? I've set up a monitoring service to alert me if the website goes down.

**Comment by wol-soft** [comment]
Hi, I can see a drop in the requests/hour rate:
![image](https://user-images.githubusercontent.com/14750468/68309344-9148d380-00ae-11ea-9ede-769c0eb79887.png)
but not a complete downtime, maybe some kind of network issue @ the hoster.. idk

If it occurs again I'll dive deeper to investigate the issue (hopefully not as I've no idea 😄).
