### ISSUE TITLE
NaNs in land of the Beer Factories

### ISSUE THREAD

**Issue by micaminoff** [wol-soft/beerplop#78]
After the update just now, land of the Beer Factories shows a bunch of material stock as NaN. Closing and reopening land of beer factories instantly completed all buildings in the queue, still at NaN for materials though.

I can't seem to export a save but if you need more info let me know. In the console I get one error:

`ReferenceError: options is not defined beerplop-init-1.64.0.min.js:3:97098
    <anonymous> https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.64.0.min.js:3
    e https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.64.0.min.js:3
    t https://wol-soft.de/apps/beerplop/dist/js/beerplop-init-1.64.0.min.js:3
`
See attached picture. 
![bild](https://user-images.githubusercontent.com/11438794/69830460-9a503f00-122d-11ea-8aa7-b982e9921529.png)

**Comment by wol-soft** [comment]
Thanks for the report! I'll have a look into it

**Comment by micaminoff** [comment]
Some more info: a page reload shows all materials at 0, and then increasing. Adding anything to the queue turns it all into NaNs. Closing the land of Beer Factories and reopening it (no page reload) causes the queue to instantly finish, and materials remain NaN.

**Comment by wol-soft** [comment]
I've reverted a change of the release causing the issue. Can you check if it also resolves your problems?
I was able to reproduce the issue with my save state. Some "free" finished jobs, yay

**Comment by micaminoff** [comment]
That seems to have resolved it! Wow, quick work 👍

**Comment by wol-soft** [comment]
Thanks again for the report, before it crashes more save states!
