### ISSUE TITLE
Unable to save game anymore, online or locally

### ISSUE THREAD

**Issue by hyppy99** [wol-soft/beerplop#79]
Sitting around Level 1 quadrillion, 47 Tredecillion plops (59.233 total).  I do use an autoclicker for clicking the beer as well as automatically clicking bottles.

Here is the console message whenever a save is attempted:

```
beerplop-game-1.64.4.min.js:3 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'beerplop' exceeded the quota.
    at GamePersistor.setLocalSaveState (https://wol-soft.de/apps/beerplop/dist/js/beerplop-game-1.64.4.min.js:3:1015131)
    at GamePersistor.<anonymous> (https://wol-soft.de/apps/beerplop/dist/js/beerplop-game-1.64.4.min.js:3:1011801)
GamePersistor.setLocalSaveState @ beerplop-game-1.64.4.min.js:3
(anonymous) @ beerplop-game-1.64.4.min.js:3
```

And here is what happens when a load is attempted:

```
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'beerplop' exceeded the quota.
    at GamePersistor.setLocalSaveState (https://wol-soft.de/apps/beerplop/dist/js/beerplop-game-1.64.4.min.js:3:1015131)
    at SaveStateController.<anonymous> (https://wol-soft.de/apps/beerplop/dist/js/beerplop-game-1.64.4.min.js:3:604495)
    at c (https://wol-soft.de/apps/beerplop/dist/js/beerplop-game-1.64.4.min.js:3:27603)
    at Object.fireWith [as resolveWith] (https://wol-soft.de/apps/beerplop/dist/js/beerplop-game-1.64.4.min.js:3:28347)
    at l (https://wol-soft.de/apps/beerplop/dist/js/beerplop-game-1.64.4.min.js:3:78549)
    at XMLHttpRequest.<anonymous> (https://wol-soft.de/apps/beerplop/dist/js/beerplop-game-1.64.4.min.js:3:80876)

beerplop-game-1.64.4.min.js:3 PUT https://wol-soft.de/apps/beerplop/save/2013 409 (Conflict)
```

**Comment by wol-soft** [comment]
Which browser are you using?

**Comment by hyppy99** [comment]
Chrome Version 78.0.3904.108 (Official Build) (64-bit).

The game was running overnight, and the saving issue crept up somewhere during that time period.  The last loadable save point seems to be from a time about halfway through the night.

**Comment by LucidCrux** [comment]
Can confirm. Even clicking on "Save States" takes a good 30 seconds to pop up the list of files. And on Firefox I get:
QuotaExceededError:
setLocalSaveState https://wol-soft.de/apps/beerplop/dist/js/beerplop-game-1.64.4.min.js:3
GamePersistor https://wol-soft.de/apps/beerplop/dist/js/beerplop-game-1.64.4.min.js:3
<anonymous> self-hosted:1017

Also have this, but not sure if it's a new one.
TypeError: this.config is null     beerplop-game-1.64.4.min.js:3:415294

**Comment by wol-soft** [comment]
I'm currently not able to reproduce the issue with my save state. Can you provide numbers for the supported localStorage of your browser (https://arty.name/localstorage.html) and the size of your Beerplop save state (execute `(new Beerplop.GamePersistor()).getSaveState().length
` in the Beerplop browser console).

There seems to be no uniform definition of the localStorage size. Current options for me would be

- compress the save state locally
- save a key in the localStorage and put all saves on the server

**Comment by wol-soft** [comment]
By the way: the online auto save is working even if the local save can't be saved, so your current progress isn't lost. The manual save doesn't work as it tries to save the current state locally and on the server (locally first, which crashes)

**Comment by hyppy99** [comment]
Online save doesn't seem to work either.  The next reload puts me back at the 1 quadrillion level, even after saving hours later at 2 quad.  I'll double check this today to make sure,

LocalStoage limit of my browser: 5200000 characters were stored successfully, but 5300000 weren't.

(new Beerplop.GamePersistor()).getSaveState().length = 4435060

**Comment by hyppy99** [comment]
Confirmed that online save states aren't functional either.  In fact, I see a "save state conflict" message when I try and interact with online saves.

Below is a screenshot of my save state configuration.  Note that my progress reverts to progress from approximately 12/2/2019 whenever I reload.

![image](https://user-images.githubusercontent.com/20598917/70153004-34741500-167c-11ea-9cf2-0e8689fd6a44.png)

**Comment by wol-soft** [comment]
I've located the issue. The counter for the total produced materials in the beer factories converted the number into a string concating each second more and more characters to the string. This results in a very large string over the time. Version 1.64.6 contains a save state fixer which corrects the number. Afterwards the size of the save states decreases massively and a save should be possible again (either manually using the save states modal or in the browser console with `plop('save')`).

Can you check if it solves the issues @hyppy99 @LucidCrux

**Comment by hyppy99** [comment]
@wol-soft that seems to have fixed it.  Bravo! Storage also dropped from 7.7MB to 3.7MB.

**Comment by LucidCrux** [comment]
Seems to have worked, and the game states box pops up much quicker as well.

**Comment by wol-soft** [comment]
@LucidCrux yeah, currently the whole save states are transferred to open the game states box (consequently multiple MB with the broken states). I've opened a new issue (#83) to fix this by loading only the displayed data.
