### ISSUE TITLE
Incorrect Achievements Awarded

### ISSUE THREAD

**Issue by LucidCrux** [wol-soft/beerplop#80]
Multiple of the factory land material achievements (get e9, e10, e11, etc) are awarded at once for many materials. Didn't look at the code, but possibly a case of copy/paste without changing values.

**Comment by wol-soft** [comment]
This issue is a result from the bug #79.

**Comment by wol-soft** [comment]
Bug #79 leads to large strings stored as total production for materials which causes the achievement checks to award them without 'earning' them. Version 1.64.6 contains a fix for the stored total production numbers. Afterwards the achievement check will work again as intended.
