### ISSUE TITLE
[Request] Option to turn off all the charting junk

### ISSUE THREAD

**Issue by LucidCrux** [wol-soft/beerplop#82]
I find most of the charting stuff useless, frequently being a flat line, more or less. I would prefer a decrease in memory / cpu usage, even if it is minor. Honestly, even if the polling was in longer intervals and spanning a longer period, for more meaningful graphs, I would still prefer the performance bump.

**Comment by wol-soft** [comment]
Added an option to turn the charting off. Additionally implemented an option to switch between linear and logarithmic scale. If a modal stays open and charting is enabled additional data points are automatically added to the charts.

**Comment by LucidCrux** [comment]
Nice. You work quick. Thank you.
