### ISSUE TITLE
Need help with Beerwarts training upgrades taking 1000 days each

### ISSUE THREAD

**Issue by SaintKarien** [wol-soft/beerplop#88]
Out of nowhere, all my upgrades now require 1000 days to upgrade each. If the only way to fix that is to restart from scratch, I think it's time for me to quit.

**Comment by wol-soft** [comment]
Hi @SaintKarien,

in a later stage of the game the training times are getting longer but there are upgrades which lead to magicians reducing the training time of each running training so they are reachable. Although in a very late stage the times got way too large so I limited them to 1000 days. I messed the calculation up, fixed it with 1.66.1 which I just released.

You can cancel the running training (takes a cooldown time until you can restart the training afterwards) and then start them with the correct time again (if you have started the 1000 days lasting trainings) If you haven't started them yet you should be fine again after updating to the latest version.

Really sorry for the issue!

**Comment by SaintKarien** [comment]
Delay kinda sucks (Shouldn't event exist imo.) since I would lose progress for 7 days(Not even counting the time taken for around 12~ upgrades for the new ones) waiting for the CD to go away on all my mages.

**Comment by wol-soft** [comment]
So you are fine with the Bugfix or do you need further assistance to remove the trainings from your save state which shouldn't take such a long time?

**Comment by SaintKarien** [comment]
I wouldn't mind waiting, but it's annoying. I just feel like there shouldn't be a need for the 7 day delay. Just make the punishment be no refunds for starting and cancelling training if that wasn't the case already. Or lower the delay time to 1 day or less.

**Comment by wol-soft** [comment]
I noticed the delay time isn't coupled with the game speed. I'll fix this in a new issue.
