### ISSUE TITLE
Unique Builds: spells djed and was don't work

### ISSUE THREAD

**Issue by 2ndK16** [wol-soft/beerplop#92]
While refactoring the Beer Factory multiplier to a ComposedValue, I noticed that the Unique Build multiplier wasn't applied correctly.
Assuming that I had fucked it up, I tested it again on wol-soft.de and got the following results for each of the spells:
- ankh works
- djed works only after reloading the page
- was doesn't do shit

Tested with Opera 64 on Manjaro Linux

**Comment by wol-soft** [comment]
Tested all three spells affecting directly after the equip and keeping the effect after a reload succesfully with 1.66.2. There were some issues with wrong listeners to the gameEventBus causing the wrong behaviour.
