### ISSUE TITLE
Auto cloning doesn't clone Bottle Cap Factories

### ISSUE THREAD

**Issue by SquaredGrunt** [wol-soft/beerplop#95]
Autocloning feature does not clone Bottle Cap Factories. As #87 is quite new, I think it's an omission.

**Comment by wol-soft** [comment]
Hi @SquaredGrunt in my save states the Bottle Cap Factories are cloned automatically. Have you set other buildings to a higher auto cloning priority so they are cloned in favour of the Bottle Cap Factories (can be configured for each building individually in the building details modal which opens when the building's icon is clicked)

**Comment by 2ndK16** [comment]
I had the same experience and had to clone my BCFs manually after all other buildings had been cloned to the max.

**Comment by SquaredGrunt** [comment]
Hello @wol-soft 
I just learned there is a priority for auto cloning :smile: So all my buildings are priority 1 and they are all cloned to the max (like @2ndK16 just said) except bottle cap factories.
That may be where the bug is.

**Comment by wol-soft** [comment]
Thanks for the further feedback. I also think it has something to do with the priorities. I've set the Bottle Cap Factories to the highest priority and, as described, the clonings are executed automatically.

**Comment by wol-soft** [comment]
I've located the issue: The Bottle Cap Factories didn't provide a default priority (which should be 1). Consequently it works if the priority was changed manually once (like in my save state) but doesn't work if the priority wasn't changed.

Should be fixed with 1.66.2

**Comment by SquaredGrunt** [comment]
The fix works, thanks !
